# docker-compose.prod.yml (本番用オーバーライドファイル)
# docker-compose.yml に対する本番環境用の差分を定義します。

services:
  remix:
    container_name: remix
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
      orm:
        condition: service_completed_successfully
    networks:
      - fukaya-lab-server # Caddy用の外部ネットワークを追加
    labels:
      caddy: oruca.fukaya-sus.lab
      caddy.reverse_proxy: "{{.Name}}:3000"
    command: sh -c "yarn start"


  api:
    container_name: api
    restart: unless-stopped
    command: sh -c "yarn start"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:3000"]
      interval: 10s
      timeout: 5s
      retries: 5

  orm:
    container_name: orm
    command: sh -c "npx prisma migrate deploy && npx prisma generate"

  postgres:
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  fukaya-lab-server:
    external: true
    name: fukaya-lab-server # Caddyなどが属する既存のネットワーク名

volumes:
  postgres_data: