# docker-compose.dev.yml (開発用オーバーライドファイル)
# docker-compose.yml に対する開発環境用の差分を定義します。

services:
  remix:
    container_name: remix_dev
    ports:
      - "5173:5173"
    volumes:
      - ./compose/remix:/app:delegated
      - /app/node_modules
    command: sh -c "yarn dev"

  api:
    container_name: api_dev
    ports:
      - "3000:3000"
    volumes:
      - ./compose/api:/app:delegated
      - /app/node_modules
    command: sh -c "yarn dev"

  orm:
    container_name: orm_dev
    volumes:
      - ./compose/orm:/app:delegated
      - /app/node_modules
    command: sh -c "npx prisma migrate dev --name init && npx prisma generate"

  # Prisma Studioは開発環境でのみ起動
  prisma_studio:
    build:
      context: ./compose/orm
    container_name: prisma_studio_dev
    ports:
      - "5555:5555"
    networks:
      - app_network
    depends_on:
      - orm
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: npx prisma studio --port 5555
    tty: true

  postgres:
    container_name: postgres_dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data_dev: